development:
  adapter: postgresql
  encoding: unicode
  database: acts_as_dashrize
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000  

production:
  adapter: postgresql
  encoding: unicode
  database: acts_as_dashrize
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  timeout: 5000 